[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_DIFY_BASE_URL = "https://api.dify.ai/v1"
  DIFY_API_KEY = "app-PBQ2sTwUEbWf4GXHFey5B4H0"
  DIFY_APP_ID = "app-PBQ2sTwUEbWf4GXHFey5B4H0"
  DIFY_WORKFLOW_ID = "88a47c57-4a02-456d-b3bf-e8c45baff08c"
